# Generated by Django 5.1.4 on 2024-12-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_compa', models.BigAutoField(help_text='Identificador único para la compañía.', primary_key=True, serialize=False, verbose_name='ID de Compañía')),
                ('compa_name', models.CharField(help_text='Nombre legal completo de la compañía.', verbose_name='Razón Social')),
                ('compa_tradename', models.CharField(help_text='Nombre comercial o marca de la compañía.', verbose_name='Nombre Comercial')),
                ('compa_doctype', models.CharField(choices=[('NI', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('OT', 'Otro')], help_text='Tipo de documento de identificación de la compañía.', max_length=2, verbose_name='Tipo de Documento')),
                ('compa_docnum', models.CharField(help_text='Número de identificación fiscal o documento legal de la compañía.', verbose_name='Número de Documento')),
                ('compa_address', models.CharField(help_text='Dirección física de la compañía.', verbose_name='Dirección')),
                ('compa_city', models.CharField(help_text='Ciudad donde está ubicada la compañía.', verbose_name='Ciudad')),
                ('compa_state', models.CharField(help_text='Departamento o estado donde está ubicada la compañía.', verbose_name='Departamento/Estado')),
                ('compa_country', models.CharField(help_text='País donde está ubicada la compañía.', verbose_name='País')),
                ('compa_industry', models.CharField(help_text='Sector industrial al que pertenece la compañía.', verbose_name='Industria')),
                ('compa_phone', models.CharField(help_text='Número de teléfono principal de la compañía.', verbose_name='Teléfono')),
                ('compa_email', models.EmailField(help_text='Dirección de correo electrónico principal de la compañía.', max_length=254, verbose_name='Correo Electrónico')),
                ('compa_website', models.URLField(blank=True, help_text='Sitio web oficial de la compañía.', verbose_name='Sitio Web')),
                ('compa_logo', models.ImageField(blank=True, help_text='Logo oficial de la compañía.', upload_to='', verbose_name='Logo')),
                ('compa_active', models.BooleanField(default=True, help_text='Indica si la compañía está activa (True) o inactiva (False).', verbose_name='Estado de la Compañía')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
            },
        ),
        migrations.CreateModel(
            name='EntityCatalog',
            fields=[
                ('id_entit', models.AutoField(help_text='Identificador único para el elemento del catálogo de entidades.', primary_key=True, serialize=False, verbose_name='ID del Catálogo de Entidad')),
                ('entit_name', models.CharField(help_text='Nombre del modelo Django asociado.', unique=True, verbose_name='Nombre de la Entidad')),
                ('entit_descrip', models.CharField(help_text='Descripción del elemento del catálogo de entidades.', verbose_name='Descripción')),
                ('entit_active', models.BooleanField(default=True, help_text='Indica si el elemento del catálogo está activo (True) o inactivo (False).', verbose_name='Estado Activo')),
                ('entit_config', models.JSONField(blank=True, help_text='Configuración adicional para el elemento del catálogo.', null=True, verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Catálogo de Entidad',
                'verbose_name_plural': 'Catálogos de Entidades',
            },
        ),
    ]
